on:
  push:
    branches:
    - release
jobs:
  build:
    name: Builds UI
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@release
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
