name: Build and deploy site to GitHub Pages

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches:
    - release
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  checkout:
    name: Checkout source
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      
  install-deps:
    name: Install npm dependencies
    runs-on: ubuntu-latest
    needs: checkout
    steps:
    - name: Install dependencies
      run: npm install
  
  # Configure pages job - gets base path for the Vite build
  configure_pages:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Pages
      uses: actions/configure-pages@v2
  
  # Build job
  build:
    name: Builds UI
    runs-on: ubuntu-latest
    needs: [configure_pages, install-deps]
    steps:
    - name: Build
      run: npm run build -- --base ${{ steps.configure-pages.outputs.base_path }}
        
  upload:
    name: Upload to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        # Upload dist folder
        path: './dist'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
